### ISSUE TITLE
Do you start using repo?

### ISSUE THREAD

**Issue by daemyung** [mtezych/root#1]
It's good! isn't it?

**Comment by mtezych** [comment]
Hi DM ;)

Yeah, I am trying it out - I like how it allows
composing multiple independent Git repositories into large multi-component projects.

However, my main concern is poor Windows support:
- https://bugs.chromium.org/p/gerrit/issues/detail?id=11314

Also, there are alternatives to Google Repo:

1. Jiri - used for development of Fuchsia OS.
- https://fuchsia.googlesource.com/jiri.git

2. depot_tools - used for development of Chromium.
- https://chromium.googlesource.com/chromium/tools/depot_tools.git
- https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools.html

This situation is kind of unfortunate, because there are already 3 different tools used at Google,
which provide alternative mechanism to Git submodules.
However, I'm not sure what can be done to reduce this fragmentation.

Mateusz
